repos:
-   repo: local
    hooks:
    -   id: flake8
        name: wemake-python-styleguide
        description: Check code style with wemake-python-styleguide
        entry: flake8
        language: python
        types: [python]
