name: wemake-python-styleguide

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.18.0
